[Desktop Entry]
Name=Anomen
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Orion
MetacityTheme=Homosapien Small
IconTheme=Humanity
GtkColorScheme=fg_color:#444444444444,bg_color:#efefebebe7e7,text_color:#333333333333,base_color:#ffffffffffff,selected_fg_color:#ffffffffffff,selected_bg_color:#b3b381816b6b,tooltip_fg_color:#ffffffffffff,tooltip_bg_color:#000000000000
CursorTheme=default
CursorSize=18
NotificationTheme=standard
