set nocompatible               " be iMproved
filetype off                   " required!
set background=dark

set rtp+=~/.vickev/vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" My Bundles here:
"
Bundle 'git@github.com:bling/vim-airline.git'
Bundle 'git@github.com:tomasr/molokai.git'
Bundle 'git@github.com:jgdavey/vim-railscasts.git'
Bundle 'git@github.com:sickill/vim-monokai.git'
Bundle 'git@github.com:tpope/vim-fugitive.git'
Bundle 'git@github.com:kien/ctrlp.vim.git'
Bundle 'git@github.com:mbbill/undotree.git'
Bundle 'git@github.com:scrooloose/syntastic.git'
Bundle 'git@github.com:scrooloose/nerdtree.git'
Bundle 'git@github.com:jistr/vim-nerdtree-tabs.git'
"Bundle "git@github.com:mihaifm/vimpanel.git"
"Bundle 'git@github.com:SirVer/ultisnips.git'
Bundle 'git@github.com:tomtom/tcomment_vim.git'
Bundle 'christoomey/vim-tmux-navigator'
Bundle "https://github.com/wookiehangover/jshint.vim.git"
Bundle "git@github.com:digitaltoad/vim-jade.git"
Bundle "git@github.com:airblade/vim-gitgutter"

syntax on                       " enable syntax highlighting
filetype plugin indent on       " required!
    
set tabstop=4           " Number of spaces for a <tab>
set shiftwidth=4        " Change the number of space characters inserted for indentation
set expandtab           " Convert <tab> to spaces
set autoindent          " Indent automatically
set incsearch           " While typing a search command, show where the pattern, as it was typed so far, matches
set wildmenu            " When 'wildmenu' is on, command-line completion operates in an enhanced mode
set scrolloff=5         " Minimal number of screen lines to keep above and below the cursor.
set hlsearch            " Highlight search
set laststatus=2        " Always show status bar

set backspace=indent,eol,start " Make backspace work

" When editing a file, always jump to the last known cursor position.
" Don't do it when the position is invalid or when inside an event handler
" (happens when dropping a file on gvim).
autocmd BufReadPost *
\ if line("'\"") > 0 && line("'\"") <= line("$") |
\   exe "normal g`\"" |
\ endif

" For gvim:
set guioptions=a
set guicursor+=a:blinkon0
set guicursor+=a:block-Cursor
set mouse=

" Set colors
set t_Co=256
set term=screen-256color
colorscheme monokai
"colorscheme railscasts

highlight SpellBad term=reverse ctermfg=15 ctermbg=9 guifg=White guibg=Red

set cursorline
set cursorcolumn

"==================================================
" Airline
"==================================================
let g:airline_theme             = 'molokai'
let g:airline_enable_branch     = 0
let g:airline_enable_syntastic  = 0
let g:airline_inactive_collapse = 0

" vim-powerline symbols
let g:airline_symbols = {}
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

let g:airline#extensions#whitespace#enabled = 0 " disable whitespace check
let g:airline#extensions#branch#enabled = 1     " enable git branch

"==================================================
" Buffer line
"==================================================
let g:bufferline_echo = 1
let g:bufferline_show_bufnr = 0

"autocmd FileType ruby source ~/.vim/script/demi_indent
"autocmd FileType javascript source ~/.vim/script/demi_indent
"autocmd FileType yml source ~/.vim/script/demi_indent
"autocmd FileType css source ~/.vim/script/demi_indent
"autocmd FileType rhtml,html,eruby source ~/.vim/script/demi_indent

"==================================================
" Numerical pad
"==================================================
inoremap Oq 1
inoremap Or 2
inoremap Os 3
inoremap Ot 4
inoremap Ou 5
inoremap Ov 6
inoremap Ow 7
inoremap Ox 8
inoremap Oy 9
inoremap Op 0
inoremap On .
inoremap Oo /
inoremap Oj *
inoremap Ok +
inoremap Om -

imap ^[OA <ESC>ki
imap ^[OB <ESC>ji
imap ^[OC <ESC>li
imap ^[OD <ESC>hi

map <f9> :NERDTreeTabsToggle<cr>
map <F2> :mksession! ~/vim_session <cr> " Quick write session with F2
map <F3> :source ~/vim_session <cr>     " And load session with F3

set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*node_modules*,*.min.js

let g:gitgutter_highlight_lines = 1
