#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=bottom height=40 blur_radius=30 padding_left=65 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:11.0"
  label.font="Hack Nerd Font:Bold:13.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

SPACE_ICONS=("1" "2" "3" "Work" "Obsidian" "Code" "Spotify" "Messages" "Email" "Perso" "Bamboo")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=7
    icon.padding_right=7
    icon.font="Hack Nerd Font:Bold:13.0"
    background.color=0x40ffffff
    background.corner_radius=20
    background.height=28
    label.drawing=off
    script="$PLUGIN_DIR/space.sh"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

# sketchybar --add item chevron left \
#            --set chevron icon= label.drawing=off \
#            --add item front_app left \
#            --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
#            --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events
mic=(
    update_freq=1
    script="$PLUGIN_DIR/mic.sh"
   # click_script="SwitchAudioSource -t input -s \"USB PnP Audio Device\" > /dev/null && osascript -e 'set volume input volume 75'"
)
speaker=(
    update_freq=1
    script="$PLUGIN_DIR/speaker.sh"
)

date=(
    update_freq=60
    script='sketchybar --set $NAME label="$(date +"%a %d %b")"'
)
time=(
    label.width=60
    y_offset=-5
    label.align=left
    update_freq=1
    script='sketchybar --set $NAME label="$(date "+%T")"'
)

sketchybar  --add item clock right \
           --set clock update_freq=10 icon=🕑  script="$PLUGIN_DIR/clock.sh" \
           --add item date right \
            --set date "${date[@]}" icon=📅   \
            \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change \
           --add item speaker right \
           --set speaker "${speaker[@]}" \
           --add item mic right \
           --set mic "${mic[@]}" 

          #  --add item volume right \
          #  --set volume script="$PLUGIN_DIR/volume.sh" \
          #  --subscribe volume volume_change \
##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
